version: '3.8'

services:
  postgres:
    image: hub.megan.ir/postgres:latest
    container_name: postgres_container_hasin
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - hasin_network
    restart: unless-stopped

  pgadmin:
    image: hub.megan.ir/dpage/pgadmin4
    container_name: pgadmin_container_hasin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - hasin_network
    restart: unless-stopped
    depends_on:
      - postgres

  redis:
    image: hub.megan.ir/redis:latest
    container_name: redis_container_hasin
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hasin_network
    restart: unless-stopped

  
  backend:
    build:
      context: .. 
      dockerfile: ./docker/Dockerfile 
    container_name: hasin_backend_container
    ports:
      - "8080:8080"
    env_file:
      - ../.env 
    networks:
      - hasin_network
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  
  frontend:
    build:
      context: ../../hasin_interview_frontend
      dockerfile: Dockerfile 
    container_name: hasin_frontend_container
    ports:
      - "3000:80"
    networks:
      - hasin_network
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  hasin_network:
    driver: bridge